name: Очередной АйТи блог

description: If you can't explain it simply, you don't understand it well enough.

avatar: https://avatars.githubusercontent.com/u/41509175

github_username: filintech

# Build settings
markdown: kramdown
remote_theme: samarsault/texture
plugins:
  - jekyll-feed

texture:
  title: Очередной АйТи блог
  tagline: If you can't explain it simply, you don't understand it well enough.
  date_format: "%b %-d, %Y"

  social_links:
    github: filintech
